language: node_js
node_js:
  - 12

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - cd lambda/custom
  - yarn
  - cd ../..

script:
  - ./hooks/build.sh
