name: ESLint

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

defaults:
  run:
    shell: bash
    working-directory: lambda/custom

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn run lint-check
